$Global:DisPlanEmpE4    = "Deskless,FLOW_O365_P2,POWERAPPS_O365_P2,MCOVOICECONF"
$Global:DisPlanNonEmpE4 = "Deskless,FLOW_O365_P2,POWERAPPS_O365_P2,YAMMER_ENTERPRISE,MCOVOICECONF,MCOSTANDARD,SHAREPOINTWAC,SHAREPOINTENTERPRISE"
$Global:DisPlanEmpE3 	 = "Deskless,FLOW_O365_P2,POWERAPPS_O365_P2"
$Global:DisPlanNonEmpE3 = "Deskless,FLOW_O365_P2,POWERAPPS_O365_P2,YAMMER_ENTERPRISE,MCOSTANDARD,SHAREPOINTWAC,SHAREPOINTENTERPRISE"